server:
  port: 8080

spring:
  application:
    name: springboot-boilerplate

  datasource:
    url: jdbc:postgresql://localhost:5432/boilerplate
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: 4a6f686e446f6553656372657456657279566572795365637265744b6579466f724a57545369676e696e6754657374
    expiration-ms: 86400000
